= To Install Anypoint Runtime Fabric (BETA)

This topic describes how to install Runtime Fabric using a command-line based installer.

[WARNING]
====
Before running the installer, ensure that your infrastructure meets the minimum hardware requirements.
====

== Prerequisites

To run the installer, ensure that you have root access on all of the servers in your environment. 

Before running the installer, you will need the following:

* The private and public IP addresses of each server in your installation.
* Acceptance to the Runtime Fabric beta program.

== Minimum hardware requirements

To set up Runtime Fabric with support for high availability, 3 servers or virtual machine instances are required with the following:

* 2 CPU cores
* 15 GiB memory
* _Disk 1_: 60GB disk space with 3000 provisioned IOPS
* _Disk 2_: 100GB disk space with at least 500 provisioned IOPS

== About the Installation Scripts and Binaries

The installation consists of the following scripts and binaries:

* `setup.sh`: installs dependencies, formats, and mounts block devices used by Runtime Fabric.
* `installer.tar.gz`: contains the installation binaries.
* `auto-installer.py`: installs Runtime Fabric on each server.

== Running the Command Line Installation

. Obtain the installation scripts and binaries by speaking with your customer service representative.
. Copy and run in privileged mode the `setup.sh` to each server node in your cluster. The script accepts 2 parameters which are required. The first parameter describes the disk block device path for _Disk 1_, while the second parameter describes the same for _Disk 2_. After running the script, you may be prompted to accept the changes. 
+
----
chmod +x setup.sh
sudo ./setup.sh /dev/sdc /dev/sdd
----
+
[NOTE]
To help identify the paths to your block devices, use `lsblk`.
+

. Copy the `installer.tar.gz` binary, the `auto-installer.py` script, and your private key to a single server or virtual machine. The installer URL can be found by navigating to Anypoint Runtime Manager, selecting the Worker Clouds tab, and clicking the Create Worker Cloud button.
+
----
wget <installer_URL> -O installer.tar.gz
----

. Move the `installer.tar.gz` binary to the user's home directory.
+
----
mv installer.tar.gz ~
----
+
[NOTE]
Ensure the installation binary file name is equal to `installer.tar.gz`.
+

. Move `auto-installer.py` to a temp directory, and change to that directory.
+
----
mv auto-installer.py /tmp/
cd /tmp/
----

. Run the following command on the same server or virtual machine to start the `auto-installer.py` script. This script requires Python 2.7 to run. The private and public IP addresses, admin username for the servers, the block device path for _Disk 2_, and the private ssh key pair should be filled in as environment variables before running.
+
----
PRIVATE_IPS="<private-ip-1> <private-ip-2> <private-ip-3> \
 PUBLIC_IPS="<public-ip-1> <public-ip-2> <public-ip-3>" \
 FLAVOR=three \
 USER=<username> \
 KEY=</path/to/private/ssh/key> \
 DOCKER_DEVICE=</dev/sdd> \
 python auto_installer.py
----
+
Using the following values:
+
[%header,cols="2*a"]
|===
|Parameter | Description
|PRIVATE_IPS | Specifies the private IP address for each server.
|PUBLIC_IPS | Specifies the public IP address for each server.
|FLAVOR | Specifies the number of nodes in your cluster. Valid values are: `one`, `three`, and `six`.
|USER | Specifies the username on the servers.
|KEY | Specifies the path for the private ssh key pair.
|DOCKER_DEVICE | Specifies the path to _Disk 2_ device on each server. Use `lsblk` to list the available devices.
|===
+
[NOTE]
This step will install Runtime Fabric across all servers to form a cluster. It may take 10-15 minutes or longer to complete.

== Registering Runtime Fabric

After the installation script has completed, you'll need to register Runtime Fabric to Anypoint Runtime Manager.

. Navigate to Runtime Manager, select the Worker Clouds tab, and select the Create Worker Cloud button.
. On Step 3, choose a name for your Runtime Fabric. Copy the script to your clipboard.
. On a server running Runtime Fabric, paste and run the registration script with a privledged user.
. After the script completes the registration process, Runtime Fabric should be registered and visible on the Runtime Fabrics tab in Runtime Manager.

== Known Issues

The following are issues which may be present during the beta program for Runtime Fabric. 

* Applications must be uploaded to Anypoint Exchange before they can be deployed to Runtime Fabric.
