= Introduction to Mule 4: DataWeave 2.0

DataWeave 2 is largely unchanged from DataWeave 1. However, MuleSoft made many improvements to make it easier to learn and added new capabilities.

== Operators Are Functions
In DataWeave 2, all operators are now functions. While this can involve more parentheses, it is less ambiguous and more friendly to learn through auto-completion features. The previous syntax continues to work for functions with two parameters, providing a shorter syntax for power users.

[cols=“1,3”]
|===
|DataWeave 1|`sizeOf payload filter $.age > 30` |
|DataWeave 2 - Function Syntax|`sizeOf(filter(payload, (value) -> value.age > 30)))` |
|DataWeave 2 - Shortcut Syntax|`sizeOf(payload filter $.age > 30)` |
|===

== Traits Are Functions

[cols=“1,3”]
|===
| DataWeave 1 | `payload is :empty` |
| DataWeave 2 | `isEmpty(payload)`  |
|===

== Type Names
DataWeave 2 uses a type name syntax, which removes the `:` from the name.

[cols=“1,3”]
|===
| DataWeave 1 | `payload.foo as :string` |
| DataWeave 2 | `payload.foo as String`  |
|===

== XML Format
The default for the reader property nullValueOn is "empty". For DataWeave 1 (Mule 3.x) it used to be "none".
script:
%dw 1.0
%output application/xml  skipNullOn="everywhere"
---
payload

input:
<book>
  <name></name>
</book>
  
DataWeave 1 output:
<book>
  <name></name>
</book>

DataWeave 2 output:
<book/>

You can get the previous behavior by setting the reader property nullValueOn="none".

== New Capabilities
There are also many new capabilities, including:
 * Typing for reusable functions
 * Multi-line comments
 * Ability to call out to Java code
 * Multipart, URL-encoded, and text readers and writers
 * Modules and imports
 * and more

== See Also

link:migration-dataweave[Migrating from DataWeave 1.0 to 2.x]

// TODO: WAIT UNTIL MEL TOPIC READY
// link:migration-mel[Migrating MEL to DataWeave]

link:dataweave[About DataWeave]
